name: Build firmware

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/hadzhioglu/padavan-ng
    defaults: { run: { shell: bash } }
    steps:
    - uses: actions/checkout@v4

    - name: Build Toolchain
      run: |
        git config --global --add safe.directory '*'
        # Kiểm tra nếu thư mục out chưa có thì build toolchain từ thư mục gốc 'toolchain'
        if [ ! -d "toolchain/out" ]; then
          echo "Building toolchain from source..."
          cd toolchain
          ./clean_toolchain
          ./build_toolchain
        else
          echo "Toolchain already built, skipping..."
        fi

    - name: Build Firmware
      run: |
        # Copy file config vào trunk
        cp build.config trunk/.config
        cd trunk
        
        # Build firmware
        ./clear_tree.sh
        ./build_firmware.sh
        
        # Tìm file kết quả
        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: trunk/images/${{ env.FW_FILE_NAME }}
        
